title: pdqdat
description: pdqdat JSON
baseurl: /hacked-jekyll
url: https://pdqdat.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
